import { NextResponse } from "next/server";

export const runtime = "nodejs";
// Keep this public doc cacheable. It changes rarely, but we may tweak copy.
export const revalidate = 3600;

const CANONICAL_ORIGIN = "https://revshare.fast";

function buildMarkdown(): string {
  const appVersion = process.env.npm_package_version ?? "0.0.0";
  const gitSha =
    process.env.VERCEL_GIT_COMMIT_SHA ??
    process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA ??
    "";

  const frontmatterLines = [
    "---",
    "name: revclaw",
    `version: ${appVersion}`,
    "description: RevClaw agent integration for RevShare. Allows OpenClaw/Clawdbot to publish projects and submit applications on behalf of users.",
    `homepage: ${CANONICAL_ORIGIN}`,
    `metadata: {\"revclaw\":{\"api_base\":\"${CANONICAL_ORIGIN}/api\",\"registration_endpoint\":\"${CANONICAL_ORIGIN}/api/revclaw/agents/register\",\"auth_instructions_url\":\"${CANONICAL_ORIGIN}/revclaw/auth.md\",\"auth_scheme\":\"bearer-access-token\"}}`,
    "---",
  ];

  if (gitSha) frontmatterLines.push(`commit_sha: ${gitSha}`);
  frontmatterLines.push("---");

  const bodyLines = [
    "",
    "# RevClaw",
    "",
    "RevClaw is RevShare’s bot integration surface for OpenClaw/Clawdbot agents. It lets an agent act **on behalf of a human** (never as the principal) to publish projects and submit applications — with approval required by default for high‑risk actions.",
    "",
    "## Skill Files",
    "",
    "| File | URL |",
    "|------|-----|",
    `| **SKILL.md** (this file) | \`${CANONICAL_ORIGIN}/skill.md\` |`,
    `| **AUTH.md** | \`${CANONICAL_ORIGIN}/revclaw/auth.md\` |`,
    "",
    "**Install locally (optional):**",
    "```bash",
    "mkdir -p ~/.openclaw/skills/revclaw",
    `curl -s ${CANONICAL_ORIGIN}/skill.md > ~/.openclaw/skills/revclaw/SKILL.md`,
    `curl -s ${CANONICAL_ORIGIN}/revclaw/auth.md > ~/.openclaw/skills/revclaw/AUTH.md`,
    "```",
    "",
    "**Base URL:** `https://revshare.fast/api`",
    "",
    "⚠️ IMPORTANT:",
    "- This file is public and contains **no secrets**.",
    "- **Never** put identity proofs, exchange codes, access tokens, or refresh tokens in URLs.",
    "",
    "## API base",
    "",
    `- Base URL: \`${CANONICAL_ORIGIN}/api\``,
    "- Registration: `POST /api/revclaw/agents/register`",
    `- Auth instructions: \`${CANONICAL_ORIGIN}/revclaw/auth.md\``,
    "",
    "## Authentication (summary)",
    "",
    "After registration + human claim/approval, the bot obtains an **access token** and calls API endpoints with:",
    "",
    "`Authorization: Bearer <access_token>`",
    "",
    "Tokens are **short-lived** (<= 15 minutes) and scoped.",
    "",
    "## Tools / actions (v0)",
    "",
    "> Names below are descriptive. Exact REST endpoints are provided.",
    "",
    "### Minimal end-to-end flow (v0)",
    "1. `POST /api/revclaw/agents/register` → receive `{ agent_id, agent_secret, claim_id, expires_at }`.",
    "2. Trigger a Telegram approval for the human (inline button callback).",
    "3. Poll `GET /api/revclaw/agents/:agent_id/claim-status` until it returns `status=claimed` + `exchange_code`.",
    "4. `POST /api/revclaw/tokens` with `{ agent_id, agent_secret, exchange_code }` → receive `{ access_token, refresh_token }`.",
    "5. Call APIs with `Authorization: Bearer <access_token>`.",
    "6. For publish/apply: create an intent → human approves → execute once (intent is single-use).",
    "",
    "## Register First",
    "",
    "Every agent starts by registering and saving its bot-only secret.",
    "",
    "```bash",
    `curl -X POST ${CANONICAL_ORIGIN}/api/revclaw/agents/register \\\n  -H "Content-Type: application/json" \\\n  -d '{"name":"YourAgent","description":"What you do","manifest_url":"https://example.com/your-skill.md"}'`,
    "```",
    "",
    "Response:",
    "```json",
    "{\n  \"agent_id\": \"...\",\n  \"agent_secret\": \"...\",\n  \"claim_id\": \"...\",\n  \"claim_url\": \"https://revshare.fast/revclaw/claim?claim_id=...\",\n  \"expires_at\": \"2026-...Z\"\n}",
    "```",
    "",
    "The bot should send `claim_url` to the human on whatever channel it has (Telegram/WhatsApp/email/etc)." ,
    "",
    "⚠️ Save `agent_secret` immediately. It is returned only once.",
    "",
    "## Claim (human approval in Telegram)",
    "",
    "RevClaw is Telegram-first: the human claims the bot inside Telegram. The server derives `telegram_user_id` from the Telegram callback context (never from bot JSON).",
    "",
    "In practice, your bot will call an endpoint (or follow a server-provided instruction) that results in RevShare sending the human an inline approval button in Telegram.",
    "",
    "## Claim status polling",
    "",
    "After the human approves, poll for claim status:",
    "",
    "```bash",
    `curl ${CANONICAL_ORIGIN}/api/revclaw/agents/$AGENT_ID/claim-status \\\n  -H "Authorization: Bearer $AGENT_SECRET"`,
    "```",
    "",
    "Response (pending):",
    "```json",
    "{ \"status\": \"pending\" }",
    "```",
    "",
    "Response (claimed):",
    "```json",
    "{ \"status\": \"claimed\", \"user_id\": \"...\", \"installation_id\": \"...\", \"granted_scopes\": [\"...\"], \"exchange_code\": \"...\" }",
    "```",
    "",
    "## Token exchange",
    "",
    "Exchange the `exchange_code` for access + refresh tokens:",
    "",
    "```bash",
    `curl -X POST ${CANONICAL_ORIGIN}/api/revclaw/tokens \\\n  -H "Content-Type: application/json" \\\n  -d '{"agent_id":"...","agent_secret":"...","exchange_code":"..."}'`,
    "```",
    "",
    "Response:",
    "```json",
    "{\n  \"access_token\": \"...\",\n  \"refresh_token\": \"...\",\n  \"expires_in\": 300,\n  \"token_type\": \"Bearer\",\n  \"scopes\": [" + "\"projects:read\"" + "]\n}",
    "```",
    "",
    "## Token refresh (rotation)",
    "",
    "Refresh tokens rotate (single-use). Send the refresh token as a Bearer token:",
    "",
    "```bash",
    `curl -X POST ${CANONICAL_ORIGIN}/api/revclaw/tokens/refresh \\\n  -H "Authorization: Bearer $REFRESH_TOKEN"`,
    "```",
    "",
    "## Intents (required for high-risk actions)",
    "",
    "Publishing projects and submitting applications require an approved intent by default.",
    "",
    "Create an intent (bot-authenticated):",
    "```bash",
    `curl -X POST ${CANONICAL_ORIGIN}/api/revclaw/intents \\\n  -H "Authorization: Bearer $AGENT_SECRET" \\\n  -H "X-RevClaw-User-Id: $USER_ID" \\\n  -H "Content-Type: application/json" \\\n  -d '{"kind":"PROJECT_PUBLISH","payload_json":{"project_id":"...","project_name":"..."},"idempotency_key":"..."}'`,
    "```",
    "",
    "Response includes:",
    "- `approval_url` (HUMAN opens this GET link to review + approve/deny)",
    "- `approve_api_url` / `deny_api_url` (POST endpoints behind the buttons)",
    "",
    "Approval flow (magic-link):",
    "1) Bot sends `approval_url` to the human over any channel (email/Signal/WhatsApp/etc).",
    "2) Human opens the link and clicks **Approve** or **Deny**.",
    "3) Bot polls `GET /api/revclaw/intents/:id` (bot-auth) until status becomes `approved` or `denied`.",
    "",
    "Once approved, execute the protected action providing the intent id in the header:",
    "`X-RevClaw-Intent-Id: <intent_id>`",
    "",
    "---",
    "",
    "### Identity + install",
    "- **verify_identity** → `POST /api/revclaw/agents/verify-identity`",
    "- **register_agent** → `POST /api/revclaw/agents/register`",
    "- **claim_status** (bot polling) → `GET /api/revclaw/agents/:agent_id/claim-status`",
    "- **token_exchange** → `POST /api/revclaw/tokens`",
    "- **token_refresh** → `POST /api/revclaw/tokens/refresh`",
    "- **revoke_installation** (human) → `POST /api/revclaw/installations/:id/revoke`",
    "",
    "### Projects",
    "- **list_projects** (read) → `GET /api/projects`",
    "- **get_project** (read) → `GET /api/projects/:id`",
    "- **create_project_draft** → `POST /api/projects`",
    "- **update_project_draft** → `PATCH /api/projects/:id`",
    "- **publish_project** (approval required by default) → via **intent** (see below)",
    "",
    "### Applications",
    "- **list_applications** (read) → `GET /api/applications`",
    "- **create_application_draft** → `POST /api/applications`",
    "- **update_application_draft** → `PATCH /api/applications/:id`",
    "- **submit_application** (approval required by default) → via **intent**",
    "",
    "### Stripe Connect",
    "For founders, Stripe Connect is completed by the human inside the dashboard (OAuth in browser).",
    "The bot should send the human to the project page with the Stripe dialog open:",
    "",
    `- Project dashboard: \`${CANONICAL_ORIGIN}/founder/projects/:id?dialog=stripe\``,
    "",
    "The dialog shows current Stripe status and a **Connect Stripe** button.",
    "",
    "(Advanced/optional) API helper:",
    "- **create_stripe_connect_link** → `POST /api/projects/:id/stripe/connect-link`",
    "",
    "### Marketer invitations + chat (recommended after project draft is created)",
    "RevShare supports founder→marketer **Invitations** and a per-project chat thread (**Conversation**).",
    "The bot should not spam or send outreach automatically — it should **recommend** marketers and provide a **draft invite message** for human review.",
    "",
    "When the bot creates a project draft, it should do the following:",
    "1) Suggest marketers that fit the project.",
    "2) Show a short example invitation message that the founder can send.",
    "3) Deep-link the founder to the dashboard invitation UI.",
    "",
    "**Recommend marketers (bot-auth, project-scoped):**",
    "- `GET /api/revclaw/projects/:id/marketers/recommendations`",
    "",
    "**Draft outreach email/message (bot-auth, project-scoped):**",
    "- `POST /api/revclaw/projects/:id/marketers/outreach-email-draft`",
    "",
    "**Invite a marketer (human in dashboard):**",
    `- Dashboard → \`${CANONICAL_ORIGIN}/founder/projects/:id?tab=invitations\``,
    "",
    "Example invite message (bot should customize):",
    "```",
    "Hey {marketer_name} — I’m the founder of {project_name}. We’re offering {commission_percent}% commission with a {refund_window_days}-day refund window.\n\nIf you’re interested, I can send you an invitation in RevShare so you can start tracking referrals and chatting in-project.",
    "```",
    "", 
    "### Coupon templates (after Stripe is connected)",
    "Coupon templates create real discounts in the founder’s connected Stripe account.",
    "Default flow: bot requests approval (intent) → then creates the template via RevClaw.",
    "Tip: omit optional fields instead of sending nulls.",
    "",
    "1) Create intent:",
    "```bash",
    `curl -X POST ${CANONICAL_ORIGIN}/api/revclaw/intents \\\n  -H "Authorization: Bearer $AGENT_SECRET" \\\n  -H "X-RevClaw-User-Id: $USER_ID" \\\n  -H "Content-Type: application/json" \\\n  -d '{"kind":"COUPON_TEMPLATE_CREATE","payload_json":{"project_id":"...","project_name":"...","name":"Launch -25%","percentOff":25,"durationType":"ONCE"},"idempotency_key":"..."}'`,
    "```",
    "2) Human opens `approval_url` and approves.",
    "3) Bot executes creation:",
    "```bash",
    `curl -X POST ${CANONICAL_ORIGIN}/api/revclaw/projects/:id/coupon-templates \\\n  -H "Authorization: Bearer $ACCESS_TOKEN" \\\n  -H "X-RevClaw-Intent-Id: $INTENT_ID" \\\n  -H "Content-Type: application/json" \\\n  -d '{"project_name":"...","name":"Launch -25%","percentOff":25,"durationType":"ONCE"}'`,
    "```",
    "",
    "Required scope: `coupons:template_write`",
    "",
    "### Plan-first workflow (single approval per plan)",
    "Bots can propose a **Plan** that batches multiple actions (project draft + rewards + coupon templates).",
    "Humans approve **once per plan** (not forever). The plan is hash-locked and cannot change after approval.",
    "",
    "### Marketer promo plans (single or batch)",
    "Marketer-bots can propose promo plans that: **apply** to projects, and if auto-approved, **generate coupon codes**, fetch **attribution links**, and generate **promo drafts** (copy only; the bot never posts).",
    "",
    "Plan kinds:",
    "- `MARKETER_PROMO_PLAN` — one project",
    "- `MARKETER_BATCH_PROMO_PLAN` — multiple projects in one approval (up to 20)",
    "",
    "Discovery helpers (bot-auth with access token):",
    "- List public projects: `GET /api/revclaw/projects?category=...&limit=...` (scope: `projects:read`)",
    "- List claimable templates: `GET /api/revclaw/projects/:id/coupon-templates` (scope: `projects:read`)",
    "- Pick best template: `GET /api/revclaw/projects/:id/coupon-templates/pick` (scope: `projects:read`)",
    "",
    "Optional convenience:",
    "- Suggest + create a batch plan in one call: `POST /api/revclaw/marketer/plans/suggest-batch` (scope: `projects:read`) → returns `plan_url`",
    "",
    "Recommended bot flow (batch):",
    "1) Pick a set of candidate projects by category fit.",
    "2) For each project, call `/coupon-templates/pick` and use `data.picked.id` as `coupon.templateId`.",
    "3) Create a `MARKETER_BATCH_PROMO_PLAN` via `POST /api/revclaw/plans` (bot-auth with agent_secret + X-RevClaw-User-Id).",
    "4) Send `plan_url` to the human for approval.",
    "5) After approval, execute via `POST /api/revclaw/plans/:id/execute` with `X-RevClaw-Intent-Id` from the approved plan.",
    "",
    "Execution semantics:",
    "- If an application is not auto-approved, that project item becomes `next=await_contract_approval` and the plan can be re-executed later.",
    "- If founder Stripe is not connected or coupon generation fails, the project item records a skipped/error step; other items continue.",
    "",
    "### Metrics (bots should iterate based on performance)",
    "After the bot generates an attribution link + coupon code, it should monitor performance and adapt messaging.",
    "",
    "Marketer metrics (bot-auth with access token; requires approved contract):",
    "- `GET /api/revclaw/projects/:id/marketer/metrics` (scope: `projects:read`) → returns clicks, installs, purchases, revenue, commission (total / 7d / 30d).",
    "",
    "Important sequencing:",
    "- The plan should create everything as **DRAFT** first.",
    "- After the draft is created, the bot should ask the user to **Connect Stripe** in the dashboard:",
    `  - ${CANONICAL_ORIGIN}/founder/projects/:id?dialog=stripe`,
    "- Only after Stripe is connected should the bot ask for **publish** approval (separate intent).",
    "",
    "1) Bot creates a plan:",
    "```bash",
    `curl -X POST ${CANONICAL_ORIGIN}/api/revclaw/plans \\\n  -H "Authorization: Bearer $AGENT_SECRET" \\\n  -H "X-RevClaw-User-Id: $USER_ID" \\\n  -H "Content-Type: application/json" \\\n  -d '{"plan_json":{"kind":"PROJECT_LAUNCH_PLAN","project":{"mode":"create","name":"My Project"},"invitations":{"enabled":true,"maxMarketers":20,"message":"Hello! We just launched {project_name} on RevShare. We offer {commission_percent}% commission with a {refund_window_days}-day refund window. If you’re interested, accept the invite to get tracking + chat access."},"rewards":[],"couponTemplates":[]},"idempotency_key":"..."}'`,
    "```",
    "2) Human opens `plan_url` and approves.",
    "3) Bot executes the approved plan:",
    "```bash",
    `curl -X POST ${CANONICAL_ORIGIN}/api/revclaw/plans/:id/execute \\\n  -H "Authorization: Bearer $ACCESS_TOKEN" \\\n  -H "X-RevClaw-Intent-Id: $INTENT_ID"`,
    "```",
    "",
    "Required scopes: `projects:draft_write`, `rewards:write` (and later `coupons:template_write` + `projects:publish` when Stripe-connected).", 
    "",
    "### Rewards",
    "Rewards can be created by the bot after human approval (intent).",
    "Rewards are created as `DRAFT` so the founder can review/edit/activate them in the dashboard.",
    "",
    "Milestone types supported by the RevClaw rewards API:",
    "- `NET_REVENUE`",
    "- `COMPLETED_SALES`",
    "- `CLICKS`",
    "- `INSTALLS`",
    "",
    "Tracking semantics:",
    "- `CLICKS` counts attribution events with `deviceId` prefixed by `click:`.",
    "- `INSTALLS` counts attribution events with `deviceId` prefixed by `install:`.",
    "- Click/install rewards unlock immediately when threshold is reached (no refund-window gating).",
    "",
    "Pre-reqs:",
    "- Agent installation must include scope `rewards:write`.",
    "- Bot must obtain an `access_token` via the normal token exchange (agent_id + agent_secret + exchange_code).",
    "",
    "Flow:",
    "1) Create intent (kind `REWARD_CREATE`):",
    "```bash",
    `curl -X POST ${CANONICAL_ORIGIN}/api/revclaw/intents \\\n  -H "Authorization: Bearer $AGENT_SECRET" \\\n  -H "X-RevClaw-User-Id: $USER_ID" \\\n  -H "Content-Type: application/json" \\\n  -d '{"kind":"REWARD_CREATE","payload_json":{"project_id":"...","project_name":"...","name":"First 100 clicks","milestoneType":"CLICKS","milestoneValue":100,"rewardType":"DISCOUNT_COUPON","rewardPercentOff":25,"fulfillmentType":"AUTO_COUPON","earnLimit":"ONCE_PER_MARKETER","availabilityType":"UNLIMITED","visibility":"PUBLIC"},"idempotency_key":"..."}'`,
    "```",
    "2) Human opens `approval_url` and approves (magic-link approval works without Telegram).",
    "3) Bot executes creation via RevClaw:",
    "```bash",
    `curl -X POST ${CANONICAL_ORIGIN}/api/revclaw/projects/:id/rewards \\\n  -H "Authorization: Bearer $ACCESS_TOKEN" \\\n  -H "X-RevClaw-Intent-Id: $INTENT_ID" \\\n  -H "Content-Type: application/json" \\\n  -d '{"project_name":"...","name":"First 25 installs","milestoneType":"INSTALLS","milestoneValue":25,"rewardType":"DISCOUNT_COUPON","rewardPercentOff":25,"fulfillmentType":"AUTO_COUPON","earnLimit":"ONCE_PER_MARKETER","availabilityType":"UNLIMITED","visibility":"PUBLIC"}'`,
    "```",
    "",
    "Notes:",
    "- Server enforces reward invariants (e.g. DISCOUNT_COUPON requires rewardPercentOff).",
    "- The created reward will be `DRAFT` (not publicly visible until activated).",
    "",
    "Required scope: `rewards:write`",
    "",
    "### Approval / intents (high-risk actions)", 
    "- **create_intent** → `POST /api/revclaw/intents`",
    "- **approve_intent** (human) → `POST /api/revclaw/intents/:id/approve`",
    "- **deny_intent** (human) → `POST /api/revclaw/intents/:id/deny`",
    "",
    "High-risk actions (publish/apply) MUST be performed through an approved intent by default.",
    "",
    "## Scopes (v0)",
    "",
    "- `revclaw:install` — register + establish an installation",
    "- `projects:read`",
    "- `projects:draft_write`",
    "- `projects:publish` *(approval required by default)*",
    "- `applications:read`",
    "- `applications:draft_write`",
    "- `applications:submit` *(approval required by default)*",
    "- `stripe:connect_link`",
    "- `coupons:template_write`",
    "- `rewards:write`",
    "- `marketers:read`",
    "- `outreach:draft`", 
    "- `coupons:claim`",
    "- (UI) invitations + chat are handled in the dashboard (no bot-send by default)",
    "",
    "## Security notes (non-negotiable)",
    "",
    "- **No secrets in URLs.** Never pass access/refresh tokens, exchange codes, or identity proofs in query strings.",
    "- **No secrets in this document.** This file is public.",
    "- All writes MUST be attributable to the human user and (if applicable) the agent.",
    "",
  ];

  return [...frontmatterLines, ...bodyLines].join("\n");
}

export async function GET() {
  const body = buildMarkdown();

  return new NextResponse(body, {
    status: 200,
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      // Public, cacheable doc; safe to cache at CDN.
      "Cache-Control": "public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400",
    },
  });
}
